### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IdkJava23** [relrelb/CPPS-PCL#19]
So I can log in with my penguin and sometimes I get an error when I go to a room on the game, or sometimes when I run the script. Interesting. Want the snippet and versions? Thanks

**Comment by relrelb** [comment]
Hey, thanks for notifying. Please provide more information about the errors you get.

**Comment by IdkJava23** [comment]
[error log.txt](https://github.com/relrelb/CPPS-PCL/files/3244992/error.log.txt)

Here are the errors. I'm not to familiar with python or threading, so I couldn't really debug it myself. Thanks for everything, would love to be able to use your software.

**Comment by relrelb** [comment]
Due to Club Penguin Rewritten's recent change in the ranking system, a player's rank can be empty, which caused the script to crash. The bug should be fixed per to the [latest commit](https://github.com/relrelb/CPPS-PCL/commit/84f1452de7191565fb698f63248b07383d90af13). Please let me know for further issues you encounter.
