### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by A0GY** [relrelb/CPPS-PCL#25]
how on earth do i actually run this im a noob 
would like if someone could Gide me

**Comment by A0GY** [comment]
also need help for club penguin rewritten

**Comment by relrelb** [comment]
Hey, thanks for being interested in my project.

In order to use it, please follow these brief instructions:
1. Install [Python 2.7](https://www.python.org/downloads/release/python-2717/) (on Windows you may want [this](https://www.python.org/ftp/python/2.7.17/python-2.7.17.amd64.msi)).
2. Open the command line and clone this repository by running `git clone https://github.com/relrelb/CPPS-PCL.git`.
3. `cd` into the cloned repository and run `python login.py` or `python multi.py`, depending on whether you want to login with and control a single penguin, or rather with multiple penguins.
4. From here you should stick to the [README](https://github.com/relrelb/CPPS-PCL/blob/master/README.md#single-login) instructions.

Please let me know if something is unclear to you or if you have/need any further questions/help.

**Comment by ALIOGY123** [comment]
I am a bit confused i have downloaded the file 
i opened the command line but what do you mean by clone this repository by running git clone https://github.com/relrelb/CPPS-PCL.git
![image](https://user-images.githubusercontent.com/57839801/69147640-63aa5400-0aca-11ea-89c6-a414b5aa360c.png)

**Comment by A0GY** [comment]
when ever i put my account that i want to be followed in multi on cpr it just keeps on saying incorrect password
