### ISSUE TITLE
How to get the host IP for a new CPPS

### ISSUE THREAD

**Issue by fm1randa** [relrelb/CPPS-PCL#30]
How can i get the host IP?

**Comment by relrelb** [comment]
Hey, thanks for interesting in my project!

This can be accomplished using [Wireshark](https://www.wireshark.org/). Login in the browser as usual while capturing packets with Wireshark, then look for TCP packets with `%xt%` in their data.
Note that sometimes there are two different host IPs: One for the initial login procedure, and one per the specific game server you choose. But usually they share the same host IP.

Please let me know if you have any further questions.

**Comment by fm1randa** [comment]
Yeah, i have more questions:
In [servers.json](https://github.com/relrelb/CPPS-PCL/blob/master/json/servers.json): 

- What is **"login":**? Is that a login port?
- What is **"magic":**?
- What is **"single_quotes": true**?
- And when fill the fields above?

**Comment by relrelb** [comment]
* `login` is a little complex:
    * It may be only the port number of the login server. In such case the `host` field is used as the host of the login server.
    * Or, it may be a full `host:port` combination, where `host` isn't used at all.
* `magic` is the salt used to encrypt your password during the login process. In most cases it can be omitted, but from some reason it varies across client versions. Fastest way is to simply try the common existing ones, but if it doesn't work you'll have to decompile `airtower.swf` in order to figure out what it is.
* `single_quotes` is another variation between different server implementations. Likewise, fastest way is to guess it.
* Sorry, but I don't understand your last question.

**Comment by fm1randa** [comment]
Thanks!
Sorry, i'm not a english fluent speaker :/

I'll try explain my last question:
How i know when i have to use `single_quotes` or `magic` field?

**Comment by relrelb** [comment]
Oh, so as I said, normally they should be omitted, but sometimes you need to guess their values / find them the hard way ;)

**Comment by fm1randa** [comment]
Okay :)
I'm so excited with your project. I'm testing it and already founded some errors. Do you mind if I open others issues #?

**Comment by relrelb** [comment]
Sure, I would very appriciate it!
