### ISSUE TITLE
Item adder doesn't work in CPR

### ISSUE THREAD

**Issue by SlimF** [relrelb/CPPS-PCL#31]
Hey, me again!

I can log in CPR now but the item adder doesn't work unless the item is currently obtainble ingame.
For example:
ai 452 will work because the Red Viking Helmet is currently obtainble ingame
ai 460 will not work because the Golden Viking helmet is not currently obtainble ingame

When you try to get an item that isn't obtaible the following shows in the terminal:
```
>>> ai 460
Adding item 460...
# Send: %xt%s%i#ai%205894%1720688%460%
# Receive: %xt%e%1720688%402%
Error #402: Item not exist
```

**Comment by fm1randa** [comment]
Same error on CPBrasil and CPOnline.

**Comment by fm1randa** [comment]
**CPBrasil:**
```
>>> ai 460
Adding item 460...
# Send: %xt%s%i#ai%913917%460%
Failed to add item 460
>>> # Receive: %xt%e%-1%402%
Error #402: Item not exist
```

**Comment by relrelb** [comment]
I'm afraid this error can't be bypased because it's up to the server.
This project doesn't do any magic, it just imitates the original browser client.
As such, if the maintainers of the server choose to prohibit a certain item from being obtained because it shouldn't be accessible via the current catalogs, this client won't be able to obtain it also.
It very much depends on the maintainers and how strict they define which items are obtainable and which aren't, so sometimes you might encounter an inaccesible item that isn't block (mistakenly or not).
