### ISSUE TITLE
How do I retrieve more server rooms?

### ISSUE THREAD

**Issue by mikey1665** [relrelb/CPPS-PCL#33]
Hello, I am wondering how do I retrieve more server rooms? For example CPO has

			"flurry": 7007,
			"alaska": 7002,
			"sleet": 7008

How do I know what number it is? 7002 is used for 2 servers then its 7008????

**Comment by turicfr** [comment]
Hello, thank you for using my project!

This number represents the port number of a specific game server, and it can be completely random.

In order to find a game server port, you will have to capture the network traffic of your browser using a packet analyzer ([Wireshark](https://www.wireshark.org/), for example) when you login to the desired server. This is also described in [issue #30](https://github.com/relrelb/CPPS-PCL/issues/30).

Please let me know if you have any further questions.

**Comment by relrelb** [comment]
Hello, thank you for using my project!

This number represents the port number of a specific game server, and it can be completely random.

In order to find a game server port, you will have to capture the network traffic of your browser using a packet analyzer ([Wireshark](https://www.wireshark.org/), for example) when you login to the desired server. This is also described in [issue #30](https://github.com/relrelb/CPPS-PCL/issues/30).

Please let me know if you have any further questions.

**Comment by mikey1665** [comment]
Thanks! I figured it out by use an old Club Penguin packet sniffing tool called WPE Pro. I was referencing your code and I updated some old Java PCL and I was able to get bots working through java!

**Comment by relrelb** [comment]
Glad you figured this out.
Club Penguin Online should be fully working now per to the [latest commit](https://github.com/relrelb/CPPS-PCL/commit/f75d4332ed6fe0c20dbcfc1a0d6e538651a1b8c9).
